# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 622)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setMinimumSize(QtCore.QSize(0, 40))
        self.top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top.setStyleSheet("background-color: #212429;\n"
"border: 0px;")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.top)
        self.label_18.setStyleSheet("font: 18pt \"Tw Cen MT\";\n"
"color: #fff;")
        self.label_18.setText("")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.top)
        self.label_19.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/logo/logo.ico"))
        self.label_19.setScaledContents(False)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setWordWrap(False)
        self.label_19.setIndent(-6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.verticalLayout.addWidget(self.top)
        self.base = QtWidgets.QFrame(self.centralwidget)
        self.base.setStyleSheet("border: 0px;\n"
"background: #292c35;")
        self.base.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base.setObjectName("base")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.base)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_frame = QtWidgets.QFrame(self.base)
        self.left_frame.setMinimumSize(QtCore.QSize(100, 0))
        self.left_frame.setMaximumSize(QtCore.QSize(80, 16777215))
        self.left_frame.setStyleSheet("background-color: #212429;\n"
"border: 0px;")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_searchPage = QtWidgets.QPushButton(self.left_frame)
        self.bt_searchPage.setMinimumSize(QtCore.QSize(40, 60))
        self.bt_searchPage.setStyleSheet("QPushButton{image: url(:/search/search.png);border-radius: 5px;}\n"
"QPushButton:hover{background:gold;}\n"
"\n"
"")
        self.bt_searchPage.setText("")
        self.bt_searchPage.setFlat(False)
        self.bt_searchPage.setObjectName("bt_searchPage")
        self.verticalLayout_2.addWidget(self.bt_searchPage)
        self.bt_addPage = QtWidgets.QPushButton(self.left_frame)
        self.bt_addPage.setMinimumSize(QtCore.QSize(0, 60))
        self.bt_addPage.setStyleSheet("QPushButton{image: url(:/add/add.png); border-radius: 5px;}\n"
"\n"
"\n"
"QPushButton:hover{background:gold;}")
        self.bt_addPage.setText("")
        self.bt_addPage.setObjectName("bt_addPage")
        self.verticalLayout_2.addWidget(self.bt_addPage)
        self.bt_updatePage = QtWidgets.QPushButton(self.left_frame)
        self.bt_updatePage.setMinimumSize(QtCore.QSize(0, 60))
        self.bt_updatePage.setStyleSheet("QPushButton{image: url(:/update/update.png); border-radius: 5px;}\n"
"QPushButton:hover{background:gold;}")
        self.bt_updatePage.setText("")
        self.bt_updatePage.setObjectName("bt_updatePage")
        self.verticalLayout_2.addWidget(self.bt_updatePage)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.bt_developer = QtWidgets.QPushButton(self.left_frame)
        self.bt_developer.setMinimumSize(QtCore.QSize(40, 60))
        self.bt_developer.setStyleSheet("QPushButton{color: gold;\n"
"font: 10pt \"Tw Cen MT\";\n"
"background-color: #212429;}\n"
"\n"
"QPushButton:hover{color: black; background: gold; border: 1px solid rgb(31, 0, 94);}")
        self.bt_developer.setObjectName("bt_developer")
        self.verticalLayout_3.addWidget(self.bt_developer)
        self.horizontalLayout.addWidget(self.left_frame)
        self.frame_page = QtWidgets.QFrame(self.base)
        self.frame_page.setStyleSheet("border: 0px;")
        self.frame_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_page.setObjectName("frame_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pages = QtWidgets.QStackedWidget(self.frame_page)
        self.pages.setStyleSheet("")
        self.pages.setObjectName("pages")
        self.pageSearch = QtWidgets.QWidget()
        self.pageSearch.setObjectName("pageSearch")
        self.gridLayout = QtWidgets.QGridLayout(self.pageSearch)
        self.gridLayout.setObjectName("gridLayout")
        self.infoTable = QtWidgets.QTableWidget(self.pageSearch)
        self.infoTable.setMinimumSize(QtCore.QSize(882, 0))
        self.infoTable.setStyleSheet("border: 1px solid;\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.infoTable.setObjectName("infoTable")
        self.infoTable.setColumnCount(8)
        self.infoTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.infoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(7, item)
        self.gridLayout.addWidget(self.infoTable, 2, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.pageSearch)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setStyleSheet("background-color: #52517b;\n"
"border-radius: 5px;\n"
"border: 1px solid;\n"
"border-color: black;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("color: #fff;\n"
"border: 0px;\n"
"font: 16pt \"Tw Cen MT\";")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.pageSearch)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_search = QtWidgets.QComboBox(self.frame_3)
        self.cb_search.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_search.setMaximumSize(QtCore.QSize(16777215, 70))
        self.cb_search.setStyleSheet("border: 1px solid;\n"
"background: #fff;\n"
"border-radius: 5px;\n"
"border-color: black;")
        self.cb_search.setObjectName("cb_search")
        self.horizontalLayout_3.addWidget(self.cb_search)
        self.btSearch = QtWidgets.QPushButton(self.frame_3)
        self.btSearch.setMaximumSize(QtCore.QSize(100, 70))
        self.btSearch.setStyleSheet("QPushButton{color: #fff;\n"
"font: 12pt \"Tw Cen MT\";\n"
"background-color: rgb(0, 0, 0); border-radius: 10px;}\n"
"\n"
"QPushButton:hover{color: black; background: gold; border: 1px solid rgb(31, 0, 94);}")
        self.btSearch.setObjectName("btSearch")
        self.horizontalLayout_3.addWidget(self.btSearch)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.pageSearch)
        self.frame_2.setMaximumSize(QtCore.QSize(100, 50))
        self.frame_2.setStyleSheet("background-color: #52517b;\n"
"border-radius: 5px;\n"
"border: 1px solid;\n"
"border-color: black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setStyleSheet("border: 0px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_nameSearch = QtWidgets.QRadioButton(self.groupBox)
        self.rb_nameSearch.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.rb_nameSearch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rb_nameSearch.setStyleSheet("font: 8pt \"Tw Cen MT\";\n"
"color: #fff;\n"
"border: 0px;\n"
"")
        self.rb_nameSearch.setObjectName("rb_nameSearch")
        self.verticalLayout_4.addWidget(self.rb_nameSearch)
        self.rb_areaSearch = QtWidgets.QRadioButton(self.groupBox)
        self.rb_areaSearch.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.rb_areaSearch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rb_areaSearch.setStyleSheet("font: 8pt \"Tw Cen MT\";\n"
"color: #fff;\n"
"border: 0px;\n"
"")
        self.rb_areaSearch.setObjectName("rb_areaSearch")
        self.verticalLayout_4.addWidget(self.rb_areaSearch)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.pages.addWidget(self.pageSearch)
        self.pageAdd = QtWidgets.QWidget()
        self.pageAdd.setObjectName("pageAdd")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageAdd)
        self.verticalLayout_6.setContentsMargins(10, 10, 0, 10)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.pageAdd)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setContentsMargins(10, 0, 40, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_5.setStyleSheet("background-color: #52517b;\n"
"border-top-left-radius: 15px;\n"
"border-bottom-left-radius: 15px;\n"
"border: 1px solid black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2.addWidget(self.frame_5, 0, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 450))
        self.frame_6.setStyleSheet("background-color: #212429;\n"
"border-top-right-radius: 15px;\n"
"border-bottom-right-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.ipt_addID = QtWidgets.QLineEdit(self.frame_6)
        self.ipt_addID.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_addID.setObjectName("ipt_addID")
        self.verticalLayout_8.addWidget(self.ipt_addID)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.ipt_addName = QtWidgets.QLineEdit(self.frame_6)
        self.ipt_addName.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_addName.setObjectName("ipt_addName")
        self.verticalLayout_8.addWidget(self.ipt_addName)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.addPageCBox = QtWidgets.QComboBox(self.frame_6)
        self.addPageCBox.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.addPageCBox.setObjectName("addPageCBox")
        self.verticalLayout_8.addWidget(self.addPageCBox)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.ipt_addAddress = QtWidgets.QLineEdit(self.frame_6)
        self.ipt_addAddress.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_addAddress.setObjectName("ipt_addAddress")
        self.verticalLayout_8.addWidget(self.ipt_addAddress)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.ipt_addEmail = QtWidgets.QLineEdit(self.frame_6)
        self.ipt_addEmail.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_addEmail.setObjectName("ipt_addEmail")
        self.verticalLayout_8.addWidget(self.ipt_addEmail)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.ipt_addPhone1 = QtWidgets.QLineEdit(self.frame_6)
        self.ipt_addPhone1.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_addPhone1.setObjectName("ipt_addPhone1")
        self.verticalLayout_8.addWidget(self.ipt_addPhone1)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.ipt_addPhone2 = QtWidgets.QLineEdit(self.frame_6)
        self.ipt_addPhone2.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_addPhone2.setObjectName("ipt_addPhone2")
        self.verticalLayout_8.addWidget(self.ipt_addPhone2)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setStyleSheet("color:#fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;\n"
"")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.ipt_addWebsite = QtWidgets.QLineEdit(self.frame_6)
        self.ipt_addWebsite.setStyleSheet("border: 0px;\n"
"border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_addWebsite.setObjectName("ipt_addWebsite")
        self.verticalLayout_8.addWidget(self.ipt_addWebsite)
        self.gridLayout_2.addWidget(self.frame_6, 0, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_save = QtWidgets.QPushButton(self.pageAdd)
        self.bt_save.setMaximumSize(QtCore.QSize(300, 50))
        self.bt_save.setStyleSheet("QPushButton{color: #fff;\n"
"font: 75 14pt \"Tw Cen MT\";\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;}\n"
"\n"
"QPushButton:hover{color: black; background: gold; border: 1px solid rgb(31, 0, 94);}\n"
"")
        self.bt_save.setObjectName("bt_save")
        self.horizontalLayout_4.addWidget(self.bt_save)
        self.bt_cancel = QtWidgets.QPushButton(self.pageAdd)
        self.bt_cancel.setMaximumSize(QtCore.QSize(300, 50))
        self.bt_cancel.setStyleSheet("QPushButton{color:#fff;\n"
"font: 75 14pt \"Tw Cen MT\";\n"
"background-color: rgb(0, 0, 0); border-radius: 10px;}\n"
"\n"
"QPushButton:hover{color: black; background: gold; border: 1px solid rgb(31, 0, 94);}")
        self.bt_cancel.setObjectName("bt_cancel")
        self.horizontalLayout_4.addWidget(self.bt_cancel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.pages.addWidget(self.pageAdd)
        self.pageUpdate = QtWidgets.QWidget()
        self.pageUpdate.setObjectName("pageUpdate")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageUpdate)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, -1, 40, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cb_searchName = QtWidgets.QComboBox(self.pageUpdate)
        self.cb_searchName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cb_searchName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"border: 1px solid black;")
        self.cb_searchName.setObjectName("cb_searchName")
        self.horizontalLayout_6.addWidget(self.cb_searchName)
        self.bt_upload = QtWidgets.QPushButton(self.pageUpdate)
        self.bt_upload.setMinimumSize(QtCore.QSize(100, 30))
        self.bt_upload.setMaximumSize(QtCore.QSize(100, 30))
        self.bt_upload.setStyleSheet("QPushButton{color: #fff;\n"
"font: 10pt \"Tw Cen MT\";\n"
"background-color: rgb(0, 0, 0);border-radius: 5px}\n"
"\n"
"QPushButton:hover{color: black; background: gold; border: 1px solid rgb(31, 0, 94);}")
        self.bt_upload.setObjectName("bt_upload")
        self.horizontalLayout_6.addWidget(self.bt_upload)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.frame_7 = QtWidgets.QFrame(self.pageUpdate)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_3.setContentsMargins(10, 0, 40, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_8.setStyleSheet("background-color: #52517b;\n"
"border-top-left-radius: 15px;\n"
"border-bottom-left-radius: 15px;\n"
"border: 1px solid black;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_3.addWidget(self.frame_8, 0, 2, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 450))
        self.frame_9.setStyleSheet("QFrame{background-color: #212429;\n"
"border-top-right-radius: 15px;\n"
"border-bottom-right-radius: 15px;\n"
"border: 1px solid black;}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        self.ipt_updateId = QtWidgets.QLineEdit(self.frame_9)
        self.ipt_updateId.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_updateId.setObjectName("ipt_updateId")
        self.verticalLayout_9.addWidget(self.ipt_updateId)
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        self.label_11.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.ipt_updateName = QtWidgets.QLineEdit(self.frame_9)
        self.ipt_updateName.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_updateName.setObjectName("ipt_updateName")
        self.verticalLayout_9.addWidget(self.ipt_updateName)
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.updatePageCBox = QtWidgets.QComboBox(self.frame_9)
        self.updatePageCBox.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.updatePageCBox.setObjectName("updatePageCBox")
        self.verticalLayout_9.addWidget(self.updatePageCBox)
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.ipt_updateAddress = QtWidgets.QLineEdit(self.frame_9)
        self.ipt_updateAddress.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_updateAddress.setObjectName("ipt_updateAddress")
        self.verticalLayout_9.addWidget(self.ipt_updateAddress)
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.ipt_updateEmail = QtWidgets.QLineEdit(self.frame_9)
        self.ipt_updateEmail.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_updateEmail.setObjectName("ipt_updateEmail")
        self.verticalLayout_9.addWidget(self.ipt_updateEmail)
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.ipt_updatePhone1 = QtWidgets.QLineEdit(self.frame_9)
        self.ipt_updatePhone1.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_updatePhone1.setObjectName("ipt_updatePhone1")
        self.verticalLayout_9.addWidget(self.ipt_updatePhone1)
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.ipt_updatePhone2 = QtWidgets.QLineEdit(self.frame_9)
        self.ipt_updatePhone2.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_updatePhone2.setObjectName("ipt_updatePhone2")
        self.verticalLayout_9.addWidget(self.ipt_updatePhone2)
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setStyleSheet("color: #fff;\n"
"font: 14pt \"Tw Cen MT\";\n"
"border: 0px;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17)
        self.ipt_updateWebsite = QtWidgets.QLineEdit(self.frame_9)
        self.ipt_updateWebsite.setStyleSheet("border-bottom: 1px solid white;\n"
"color: #fff;\n"
"font: 75 12pt \"Tw Cen MT\";\n"
"background-color: #212429;")
        self.ipt_updateWebsite.setObjectName("ipt_updateWebsite")
        self.verticalLayout_9.addWidget(self.ipt_updateWebsite)
        self.gridLayout_3.addWidget(self.frame_9, 0, 3, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bt_updateInfo = QtWidgets.QPushButton(self.pageUpdate)
        self.bt_updateInfo.setMaximumSize(QtCore.QSize(300, 50))
        self.bt_updateInfo.setStyleSheet("QPushButton{color: #fff;\n"
"font: 75 14pt \"Tw Cen MT\";\n"
"background-color: rgb(0, 0, 0);border-radius: 10px}\n"
"\n"
"QPushButton:hover{color: black; background: gold; border: 1px solid rgb(31, 0, 94);}\n"
"")
        self.bt_updateInfo.setObjectName("bt_updateInfo")
        self.horizontalLayout_5.addWidget(self.bt_updateInfo)
        self.bt_deleteData = QtWidgets.QPushButton(self.pageUpdate)
        self.bt_deleteData.setMaximumSize(QtCore.QSize(300, 50))
        self.bt_deleteData.setStyleSheet("QPushButton{color: #fff;\n"
"font: 75 14pt \"Tw Cen MT\";\n"
"background-color: rgb(0, 0, 0);border-radius: 10px}\n"
"\n"
"QPushButton:hover{color: black; background: gold; border: 1px solid rgb(31, 0, 94);}")
        self.bt_deleteData.setObjectName("bt_deleteData")
        self.horizontalLayout_5.addWidget(self.bt_deleteData)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.pages.addWidget(self.pageUpdate)
        self.horizontalLayout_2.addWidget(self.pages)
        self.horizontalLayout.addWidget(self.frame_page)
        self.verticalLayout.addWidget(self.base)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Supplier Mananger"))
        self.bt_developer.setText(_translate("MainWindow", "Created by\n"
" Renato Dantas"))
        item = self.infoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.infoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.infoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "AREA"))
        item = self.infoTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ADDRESS"))
        item = self.infoTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "E-MAIL"))
        item = self.infoTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PHONE"))
        item = self.infoTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "PHONE"))
        item = self.infoTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "WEBSITE"))
        self.label.setText(_translate("MainWindow", "Search table"))
        self.btSearch.setText(_translate("MainWindow", "SEARCH"))
        self.rb_nameSearch.setText(_translate("MainWindow", "Name Search"))
        self.rb_areaSearch.setText(_translate("MainWindow", "Area Search"))
        self.label_20.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "NAME"))
        self.label_4.setText(_translate("MainWindow", "AREA"))
        self.label_5.setText(_translate("MainWindow", "ADDRESS"))
        self.label_6.setText(_translate("MainWindow", "E-MAIL"))
        self.label_7.setText(_translate("MainWindow", "PHONE"))
        self.label_8.setText(_translate("MainWindow", "PHONE"))
        self.label_9.setText(_translate("MainWindow", "WEBSITE"))
        self.bt_save.setText(_translate("MainWindow", "SAVE"))
        self.bt_cancel.setText(_translate("MainWindow", "CANCEL"))
        self.bt_upload.setText(_translate("MainWindow", "UPLOAD"))
        self.label_21.setText(_translate("MainWindow", "ID"))
        self.label_11.setText(_translate("MainWindow", "NAME"))
        self.label_12.setText(_translate("MainWindow", "AREA"))
        self.label_13.setText(_translate("MainWindow", "ADDRESS"))
        self.label_14.setText(_translate("MainWindow", "E-MAIL"))
        self.label_15.setText(_translate("MainWindow", "PHONE"))
        self.label_16.setText(_translate("MainWindow", "PHONE"))
        self.label_17.setText(_translate("MainWindow", "WEBSITE"))
        self.bt_updateInfo.setText(_translate("MainWindow", "UPDATE INFO"))
        self.bt_deleteData.setText(_translate("MainWindow", "DELETE DATA"))
import Icones_rc
