# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(800, 600)
        self.loginWidget = QtWidgets.QWidget(loginWindow)
        self.loginWidget.setObjectName("loginWidget")
        self.frame = QtWidgets.QFrame(self.loginWidget)
        self.frame.setGeometry(QtCore.QRect(120, 100, 341, 421))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.42, y1:0.533909, x2:1, y2:0, stop:0.113636 rgba(18, 18, 0, 255), stop:0.607955 rgba(45, 13, 122, 255), stop:0.857955 rgba(68, 18, 250, 255), stop:0.971591 rgba(68, 0, 223, 255));\n"
"border-bottom-left-radius: 100px;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 141, 41))
        self.label_2.setStyleSheet("color: #fff;\n"
"background: none;\n"
"font: 16pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 141, 41))
        self.label_3.setStyleSheet("color: #fff;\n"
"background: none;\n"
"font: 16pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.ipt_user = QtWidgets.QLineEdit(self.frame)
        self.ipt_user.setGeometry(QtCore.QRect(60, 120, 241, 20))
        self.ipt_user.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ipt_user.setStyleSheet("border-bottom: 1px solid white;\n"
"background: rgb(33, 0, 99);\n"
"color: #fff;\n"
"border-radius: none;")
        self.ipt_user.setObjectName("ipt_user")
        self.ipt_password = QtWidgets.QLineEdit(self.frame)
        self.ipt_password.setGeometry(QtCore.QRect(60, 190, 241, 20))
        self.ipt_password.setStyleSheet("border-bottom: 1px solid white;\n"
"background: rgb(33, 0, 99);\n"
"color: #fff;\n"
"border-radius: none;")
        self.ipt_password.setObjectName("ipt_password")
        self.bt_login = QtWidgets.QPushButton(self.frame)
        self.bt_login.setGeometry(QtCore.QRect(60, 220, 75, 23))
        self.bt_login.setStyleSheet("QPushButton{background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255); border-radius: 5px;}\n"
"\n"
"QPushButton:hover{background: gold; color: black;}")
        self.bt_login.setObjectName("bt_login")
        self.bt_cancel = QtWidgets.QPushButton(self.frame)
        self.bt_cancel.setGeometry(QtCore.QRect(220, 220, 75, 23))
        self.bt_cancel.setStyleSheet("QPushButton{background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255); border-radius: 5px;}\n"
"\n"
"QPushButton:hover{background: gold; color: black;}")
        self.bt_cancel.setObjectName("bt_cancel")
        self.frame_2 = QtWidgets.QFrame(self.loginWidget)
        self.frame_2.setGeometry(QtCore.QRect(200, 370, 301, 191))
        self.frame_2.setStyleSheet("border: 10px solid rgb(33, 0, 99);\n"
"border-radius: 40px;\n"
"background: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: none;\n"
"color: #fff;\n"
"border-top: none;\n"
"border-left:none;\n"
"border-radius: 0px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        loginWindow.setCentralWidget(self.loginWidget)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "MainWindow"))
        self.label_2.setText(_translate("loginWindow", "USER"))
        self.label_3.setText(_translate("loginWindow", "PASSWORD"))
        self.bt_login.setText(_translate("loginWindow", "LOGIN"))
        self.bt_cancel.setText(_translate("loginWindow", "CANCEL"))
        self.label.setText(_translate("loginWindow", "Supplier\n"
"Management"))
